# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Brug den nyeste version
    hooks:
      - id: trailing-whitespace  # Fjerner unødvendige mellemrum
      - id: end-of-file-fixer    # Sikrer, at filen slutter med en ny linje
      - id: check-yaml           # Validerer YAML-filer
      - id: check-json           # Validerer JSON-filer
      - id: check-added-large-files  # Advarer, hvis du committer store filer

