name: Evaluate Model

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:  # Manuelt trigger

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Tjek kode ud
      uses: actions/checkout@v3

    - name: Sæt Python op
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer afhængigheder
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Kør evaluering
      run: |
        python wandb_evaluate.py
