_wandb:
    value:
        cli_version: 0.20.0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 2
                - 55
            "4": 3.10.12
            "5": 0.20.0
            "10":
                - 20
            "12": 0.20.0
            "13": linux-x86_64
